FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# cthulhu

クトゥルフ神話に使うキャラの操作を行うAPI

## 特定のユーザーの操作 [/users/{id}]
+ Parameters
    + id (number) ... メンバーのID

### user_show [GET]
+ Response 200 (application/json)

        {
            "name" : "nyaruko",
            "list" : [
                {
                    "id": "skill",
                    "parameter": 15
                }
            ]
        }

### user_update [PUT]
+ Request (application/json)

        {
            "name" : "nyaruko",
            "list" : [
                {
                    "id": "skill",
                    "parameter": 15
                }
            ]
        }

+ Response 200 (application/json)

        {
            "published_at": "2015-08-05T08:40:51.620Z"
        }

### user_delete [DELETE]
+ Response 200 (application/json)

        {
            "msg" : "success"
        }
        
## ユーザーの作成 [/users]

### user_create [POST]
+ Request (application/json)

        {
            "name" : "nyaruko",
            "list" : [
                {
                    "id": "skill",
                    "parameter": 15
                }
            ]
        }

+ Response 201 (application/json)
        
        {
            "id" : 15
            "published_at": "2015-08-05T08:40:51.620Z"
        }